# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Visualization for Plant Pathologists
description:      'Teaching plant pathologists the data visualization tools to show their awesome work'
url:              https://ufvegpathology.github.io/phyto-data-viz
baseurl:          /phyto-data-viz
email:            pcvgt@ufl.edu
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Nicholas Dufault & James Fulton'
  #url:            https://twitter.com/ethanwhite

github:
  repo:           https://UFVegPathology/phyto-data-viz
  #               Be sure the 'Issues' feature is activated in 'Settings'
